export const CHANGE_CARDNAME = "CHANGE_CARDNAME ";

export const SELECT_COLOR = "SELECT_COLOR";
export const RESET_COLOR = "RESET_COLOR";

export const COLORS_CHECKBOX_CHECKED = "COLORS_CHECKBOX_CHECKED";
export const COLORS_CHECKBOX_RESET = "COLORS_CHECKBOX_RESET";

export const SET_IS_CLICKED = "SET_IS_CLICKED";

export const PAGE_NUMBER_INCREMENT = "PAGE_NUMBER_INCREMENT";
export const PAGE_NUMBER_RESET = "PAGE_NUMBER_RESET";

export const SELECT_RARITY = "SELECT_RARITY";

export const SET_STATUS = "SET_STATUS";

export const SELECT_TYPE = "SELECT_TYPE";
